version: "3.9"

services:
  # ─── MySQL (for auth_service) ──────────────────────────
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD:-rootpassword}"
      MYSQL_DATABASE:    "${MYSQL_DATABASE:-geodb}"
      MYSQL_USER:        "${MYSQL_USER:-root}"
      MYSQL_PASSWORD:    "${MYSQL_PASSWORD:-rootpassword}"
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ─── MongoDB (for game_service + leaderboards) ─────────
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  # ─── Redis (for Celery backend) ────────────────────────
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"

  # ─── RabbitMQ (for all events) ─────────────────────────
  rabbitmq:
    image: rabbitmq:3.13-management
    restart: unless-stopped
    ports:
      - "5672:5672"    # AMQP
      - "15672:15672"  # Management UI
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # ─── Auth Service ─────────────────────────────────────
  auth_service:
    build: ./services/auth_service
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8001
    environment:
      MYSQL_HOST:     mysql
      MYSQL_USER:     "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      RABBITMQ_HOST:  rabbitmq
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    ports:
      - "8001:8001"

  # ─── Game Service ─────────────────────────────────────
  game_service:
    build: ./services/game_service
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8002
    environment:
      MONGO_URI:     mongodb://mongo:27017
      RABBITMQ_HOST: rabbitmq
    depends_on:
      - mongo
      - rabbitmq
    ports:
      - "8002:8002"

  # ─── Image Service ────────────────────────────────────
  image_service:
    build: ./services/image_service
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8003
    environment:
      MONGO_URI: mongodb://mongo:27017
    depends_on:
      - mongo
    ports:
      - "8003:8003"

  # ─── Leaderboards API ────────────────────────────────
  leaderboards_api:
    build: ./services/leaderboards
    env_file:
      - .env
    command: uvicorn app.app:app --host 0.0.0.0 --port 8000
    environment:
      MONGO_URI:     mongodb://mongo:27017/geo
      REDIS_HOST:    redis
      RABBITMQ_HOST: rabbitmq
      MAIL_USER:     "${MAIL_USER}"
      MAIL_PASS:     "${MAIL_PASS}"
    depends_on:
      - mongo
      - rabbitmq
    ports:
      - "8000:8000"

  # ─── Leaderboards Celery Worker + Beat ───────────────
  leaderboard_worker:
    build: ./services/leaderboards
    env_file:
      - .env
    command: celery -A app.tasks worker --beat --loglevel=info
    environment:
      MONGO_URI:     mongodb://mongo:27017/geo
      REDIS_HOST:    redis
      RABBITMQ_HOST: rabbitmq
      MAIL_USER:     "${MAIL_USER}"
      MAIL_PASS:     "${MAIL_PASS}"
    depends_on:
      - rabbitmq
      - redis
      - mongo

volumes:
  mongo_data:
  mysql_data: