groups:
  - name: rabbitmq-alerts
    rules:
      - alert: RabbitMQQueueStuck
        expr: rabbitmq_queue_messages_ready > 0
        for: 10s
        labels:
          severity: warning
        annotations:
          summary: "One or more RabbitMQ queues have stuck messages"
          description: "At least one queue has messages that are not being consumed (messages_ready > 0) for over 1 minute. This may indicate a service failure or dead letter condition."
