apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
      - name: notification
        image: vhanert/geoguessr-backend-notification_service:latest
        ports:
        - containerPort: 8000
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
        - name: EMAIL_USER
          value: "georggaetter@gmail.com"
        - name: EMAIL_PASS
          value: "okot pfeq ddgk brhp"
        - name: EMAIL_HOST
          value: "localhost"
        - name: EMAIL_PORT
          value: "1025"
        - name: AMQP_URL
          value: "amqp://guest:guest@rabbitmq:5672/"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
  - port: 8000
    targetPort: 8000