apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
        - name: notification
          image: geoguessr.azurecr.io/geoguessr-backend-notification_service:latest
          ports:
            - containerPort: 8000
          env:
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: EMAIL_USER
              value: "georggaetter@gmail.com"
            - name: EMAIL_PASS
              value: "okot pfeq ddgk brhp"
            - name: EMAIL_HOST
              value: "localhost"
            - name: EMAIL_PORT
              value: "1025"
            - name: AMQP_URL
              value: "amqp://guest:guest@rabbitmq:5672/"
          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            requests:
              memory: "32Mi"
              cpu: "20m"
            limits:
              memory: "128Mi"
              cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  type: ClusterIP
  ports:
    - name: "8005"
      port: 8005
      targetPort: 8000
---