apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      imagePullSecrets:
              - name: acr-secret
      containers:
      - name: notification
        image: geoguessr.azurecr.io/geoguessr-backend-notification_service:latest
        ports:
        - containerPort: 8000
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - name: "8005"
      port: 8005
      targetPort: 8000